# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initPackage <- function() {
    invisible(.Call(`_rkdMotifs_initPackage`))
}

setCudaUsage <- function(use_cuda) {
    invisible(.Call(`_rkdMotifs_setCudaUsage`, use_cuda))
}

setNCores <- function(ncores) {
    invisible(.Call(`_rkdMotifs_setNCores`, ncores))
}

setVerbosity <- function(verbosity) {
    invisible(.Call(`_rkdMotifs_setVerbosity`, verbosity))
}

setgMethodsSeed <- function(seed) {
    invisible(.Call(`_rkdMotifs_setgMethodsSeed`, seed))
}

test_convert_internal <- function(bed) {
    .Call(`_rkdMotifs_test_convert_internal`, bed)
}

readBedFile_internal <- function(filename, type) {
    .Call(`_rkdMotifs_readBedFile_internal`, filename, type)
}

remove_overlapping_internal <- function(bedData, type) {
    .Call(`_rkdMotifs_remove_overlapping_internal`, bedData, type)
}

background_internal <- function(regions, regionsType, excludedRegions, excludedRegionsType, ngcbins, nrpbins, nregions, referenceFileName) {
    .Call(`_rkdMotifs_background_internal`, regions, regionsType, excludedRegions, excludedRegionsType, ngcbins, nrpbins, nregions, referenceFileName)
}

get_sequences_internal <- function(bedData, type, fileName) {
    .Call(`_rkdMotifs_get_sequences_internal`, bedData, type, fileName)
}

kdistr_internal <- function(sequences, kmerlength, ngaps, doubleStrand, estimatekmers = FALSE, strict = FALSE, use_float = FALSE) {
    .Call(`_rkdMotifs_kdistr_internal`, sequences, kmerlength, ngaps, doubleStrand, estimatekmers, strict, use_float)
}

kdistrProfile_internal <- function(sequence, win, kmerlength, ngaps, doubleStrand, estimatekmers = FALSE, strict = FALSE, use_float = FALSE) {
    .Call(`_rkdMotifs_kdistrProfile_internal`, sequence, win, kmerlength, ngaps, doubleStrand, estimatekmers, strict, use_float)
}

kdmGkmersString_internal <- function(kmerlength, ngaps, doubleStrand) {
    .Call(`_rkdMotifs_kdmGkmersString_internal`, kmerlength, ngaps, doubleStrand)
}

kdmotifs_internal <- function(kdistr, rank, np, initialization_method, W0, clustering_method, battacharyya, init_only, tolerance, maxIterations, use_float) {
    .Call(`_rkdMotifs_kdmotifs_internal`, kdistr, rank, np, initialization_method, W0, clustering_method, battacharyya, init_only, tolerance, maxIterations, use_float)
}

kdmotifs_from_sequences_internal <- function(sequences, kmerlength, ngaps, double_strand, estimate, rank, np, initialization_method, W0, clustering_method, battacharyya, init_only, tolerance, maxIterations, use_float) {
    .Call(`_rkdMotifs_kdmotifs_from_sequences_internal`, sequences, kmerlength, ngaps, double_strand, estimate, rank, np, initialization_method, W0, clustering_method, battacharyya, init_only, tolerance, maxIterations, use_float)
}

kdmotifs_estimate_internal <- function(motifs, use_float) {
    .Call(`_rkdMotifs_kdmotifs_estimate_internal`, motifs, use_float)
}

kdmotifs_internal_from_motifs <- function(kdmotifs, rank, np, initialization_method, W0, clustering_method, battacharyya, init_only, tolerance, maxIterations, use_float) {
    .Call(`_rkdMotifs_kdmotifs_internal_from_motifs`, kdmotifs, rank, np, initialization_method, W0, clustering_method, battacharyya, init_only, tolerance, maxIterations, use_float)
}

kdmotifs_merge_internal <- function(kdmotifs, labels, rank, use_float) {
    .Call(`_rkdMotifs_kdmotifs_merge_internal`, kdmotifs, labels, rank, use_float)
}

kdmSilhouette_internal <- function(distance, clusterLabels, use_float) {
    .Call(`_rkdMotifs_kdmSilhouette_internal`, distance, clusterLabels, use_float)
}

kdmGetW0_internal <- function(counts, clustering_method, good_clusters, minRank, maxRank, bhattacharyya, use_float) {
    .Call(`_rkdMotifs_kdmGetW0_internal`, counts, clustering_method, good_clusters, minRank, maxRank, bhattacharyya, use_float)
}

kdmRankInfo_internal <- function(distance, clustering_method, use_float) {
    .Call(`_rkdMotifs_kdmRankInfo_internal`, distance, clustering_method, use_float)
}

kdmotifsfrompwm_internal <- function(pwmset, kmerlength, ngaps, doubleStrand, pad_size, use_float) {
    .Call(`_rkdMotifs_kdmotifsfrompwm_internal`, pwmset, kmerlength, ngaps, doubleStrand, pad_size, use_float)
}

kdmotifsfrompwm2_internal <- function(pwmset, kmerlength, ngaps, doubleStrand, use_float) {
    .Call(`_rkdMotifs_kdmotifsfrompwm2_internal`, pwmset, kmerlength, ngaps, doubleStrand, use_float)
}

kdmGetPWMThresholds_internal <- function(pwmset, alpha, initialGranularity, forcedGranularity, maxGranularity) {
    .Call(`_rkdMotifs_kdmGetPWMThresholds_internal`, pwmset, alpha, initialGranularity, forcedGranularity, maxGranularity)
}

kdmotifsReduce_internal <- function(kmotifs, rank, tolerance = 1e-6, maxIterations = 20000L, use_float = FALSE) {
    .Call(`_rkdMotifs_kdmotifsReduce_internal`, kmotifs, rank, tolerance, maxIterations, use_float)
}

kdfeatures_internal_from_kdistr <- function(motifs, kdistr, use_float) {
    .Call(`_rkdMotifs_kdfeatures_internal_from_kdistr`, motifs, kdistr, use_float)
}

kdfeatures_internal_from_seqs <- function(motifs, sequences, strict, use_float) {
    .Call(`_rkdMotifs_kdfeatures_internal_from_seqs`, motifs, sequences, strict, use_float)
}

kdfeatures_profile_internal <- function(motifs, sequence, win, strict, use_float) {
    .Call(`_rkdMotifs_kdfeatures_profile_internal`, motifs, sequence, win, strict, use_float)
}

kdmToKdistr_internal <- function(m, use_float = TRUE) {
    .Call(`_rkdMotifs_kdmToKdistr_internal`, m, use_float)
}

kdmToKDMotifs_internal <- function(d, use_float = TRUE) {
    .Call(`_rkdMotifs_kdmToKDMotifs_internal`, d, use_float)
}

kdmSimilarity_kdistr_internal <- function(d1, d2, use_float = FALSE) {
    .Call(`_rkdMotifs_kdmSimilarity_kdistr_internal`, d1, d2, use_float)
}

kdmSimilarity_kdmotifs_internal <- function(d1, d2, use_float = FALSE) {
    .Call(`_rkdMotifs_kdmSimilarity_kdmotifs_internal`, d1, d2, use_float)
}

kdmDistance_kdistr_internal <- function(d1, d2, bhattacharyya, use_float = FALSE) {
    .Call(`_rkdMotifs_kdmDistance_kdistr_internal`, d1, d2, bhattacharyya, use_float)
}

kdmDistance_kdmotifs_internal <- function(d1, d2, bhattacharyya, use_float = FALSE) {
    .Call(`_rkdMotifs_kdmDistance_kdmotifs_internal`, d1, d2, bhattacharyya, use_float)
}

kdmSimilarity_kdistr_self_internal <- function(d1, use_float = FALSE) {
    .Call(`_rkdMotifs_kdmSimilarity_kdistr_self_internal`, d1, use_float)
}

kdmSimilarity_kdmotifs_self_internal <- function(d1, use_float = FALSE) {
    .Call(`_rkdMotifs_kdmSimilarity_kdmotifs_self_internal`, d1, use_float)
}

kdmDistance_kdistr_self_internal <- function(d1, bhattacharyya, use_float = FALSE) {
    .Call(`_rkdMotifs_kdmDistance_kdistr_self_internal`, d1, bhattacharyya, use_float)
}

kdmDistance_kdmotifs_self_internal <- function(d1, bhattacharyya, use_float = FALSE) {
    .Call(`_rkdMotifs_kdmDistance_kdmotifs_self_internal`, d1, bhattacharyya, use_float)
}

kdmModelCorrelation_internal <- function(a, b, niter = 0L, use_float = FALSE) {
    .Call(`_rkdMotifs_kdmModelCorrelation_internal`, a, b, niter, use_float)
}

kdmModelCorrelation2_internal <- function(a, b, niter = 0L, use_float = FALSE) {
    .Call(`_rkdMotifs_kdmModelCorrelation2_internal`, a, b, niter, use_float)
}

predict_internal_from_features <- function(model, features, use_float = FALSE) {
    .Call(`_rkdMotifs_predict_internal_from_features`, model, features, use_float)
}

predict_internal_from_kdistr <- function(model, kdistr, use_float = FALSE) {
    .Call(`_rkdMotifs_predict_internal_from_kdistr`, model, kdistr, use_float)
}

predict_internal_from_sequences <- function(model, sequences, strict = FALSE, use_float = FALSE) {
    .Call(`_rkdMotifs_predict_internal_from_sequences`, model, sequences, strict, use_float)
}

predict_internal_from_bed <- function(model, bedData, bedType, filename, strict = FALSE, use_float = FALSE) {
    .Call(`_rkdMotifs_predict_internal_from_bed`, model, bedData, bedType, filename, strict, use_float)
}

kdmLoadPWMSet <- function(filename) {
    .Call(`_rkdMotifs_kdmLoadPWMSet`, filename)
}

kdmFeaturesFromPWMSet_internal <- function(sequences, pwmset, double_strand, mode) {
    .Call(`_rkdMotifs_kdmFeaturesFromPWMSet_internal`, sequences, pwmset, double_strand, mode)
}

kdmFeaturesProfileFromPWMSet_internal <- function(sequence, pwmset) {
    .Call(`_rkdMotifs_kdmFeaturesProfileFromPWMSet_internal`, sequence, pwmset)
}

kdmMotifProfiles2_internal <- function(bedData, centers, labels, motifs, halfInterval, halfWin, genomeFile, strict, use_float) {
    .Call(`_rkdMotifs_kdmMotifProfiles2_internal`, bedData, centers, labels, motifs, halfInterval, halfWin, genomeFile, strict, use_float)
}

kdmMotifProfiles3_internal <- function(bedData, centers, labels, motifs, halfInterval, halfWin, genomeFile, strict, use_float) {
    .Call(`_rkdMotifs_kdmMotifProfiles3_internal`, bedData, centers, labels, motifs, halfInterval, halfWin, genomeFile, strict, use_float)
}

kdmMotifProfiles3_seq_internal <- function(pseq, nseq, motifs, halfInterval, halfWin, strict, use_float) {
    .Call(`_rkdMotifs_kdmMotifProfiles3_seq_internal`, pseq, nseq, motifs, halfInterval, halfWin, strict, use_float)
}

kdmGetProfilesParameters_internal <- function(profile, halfInterval, halfWin, nrep, maxSelectedPeak, half90Interval, use_float) {
    .Call(`_rkdMotifs_kdmGetProfilesParameters_internal`, profile, halfInterval, halfWin, nrep, maxSelectedPeak, half90Interval, use_float)
}

kdmMotifProfiles_internal <- function(bedData, centers, labels, motifs, interval, win, nrep, maxSelectedPeak, half90interval, genomeFile, use_float) {
    .Call(`_rkdMotifs_kdmMotifProfiles_internal`, bedData, centers, labels, motifs, interval, win, nrep, maxSelectedPeak, half90interval, genomeFile, use_float)
}

kdmGetPWM_internal <- function(W, len, pwm0, tol, maxIter, use_float) {
    .Call(`_rkdMotifs_kdmGetPWM_internal`, W, len, pwm0, tol, maxIter, use_float)
}

kdmProfileInfo_internal <- function(motifs, regions, centers, labels, genomeFile, halfInterval, halfWin, tolerance, strict, use_float) {
    .Call(`_rkdMotifs_kdmProfileInfo_internal`, motifs, regions, centers, labels, genomeFile, halfInterval, halfWin, tolerance, strict, use_float)
}

kdmProfileInfoSeq_internal <- function(motifs, pseq, nseq, halfInterval, halfWin, tolerance, strict, use_float) {
    .Call(`_rkdMotifs_kdmProfileInfoSeq_internal`, motifs, pseq, nseq, halfInterval, halfWin, tolerance, strict, use_float)
}

kdmCentrimo_internal <- function(pcounts, ncounts, npseqs, nnseqs, tail, symmetric, use_float) {
    .Call(`_rkdMotifs_kdmCentrimo_internal`, pcounts, ncounts, npseqs, nnseqs, tail, symmetric, use_float)
}

