#pragma once
//Configuration generated by cmake
#define HAS_BOOST
#define HAS_ZLIB
#define HAS_OPENCL
#define HAS_OPENMP
#define HAS_GECO_BASE
#define HAS_GECO_UTILS
#define HAS_STATS
#define HAS_NMF
#define HAS_HCLUST
#define HAS_GECO_METHODS
#define HAS_KDMOTIFS
#define HAS_GECO_TOOLS
#define HAS_GECO_GENOMES
