// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// setCudaUsage
void setCudaUsage(bool use_cuda);
RcppExport SEXP _rkdMotifs_setCudaUsage(SEXP use_cudaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type use_cuda(use_cudaSEXP);
    setCudaUsage(use_cuda);
    return R_NilValue;
END_RCPP
}
// setNCores
void setNCores(int ncores);
RcppExport SEXP _rkdMotifs_setNCores(SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    setNCores(ncores);
    return R_NilValue;
END_RCPP
}
// setVerbosity
void setVerbosity(unsigned short verbosity);
RcppExport SEXP _rkdMotifs_setVerbosity(SEXP verbositySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned short >::type verbosity(verbositySEXP);
    setVerbosity(verbosity);
    return R_NilValue;
END_RCPP
}
// setgMethodsSeed
void setgMethodsSeed(float seed);
RcppExport SEXP _rkdMotifs_setgMethodsSeed(SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type seed(seedSEXP);
    setgMethodsSeed(seed);
    return R_NilValue;
END_RCPP
}
// test_convert_internal
std::vector<std::string> test_convert_internal(const DataFrame& bed);
RcppExport SEXP _rkdMotifs_test_convert_internal(SEXP bedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type bed(bedSEXP);
    rcpp_result_gen = Rcpp::wrap(test_convert_internal(bed));
    return rcpp_result_gen;
END_RCPP
}
// readBedFile_internal
DataFrame readBedFile_internal(const std::string& filename, const std::string& type);
RcppExport SEXP _rkdMotifs_readBedFile_internal(SEXP filenameSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(readBedFile_internal(filename, type));
    return rcpp_result_gen;
END_RCPP
}
// remove_overlapping_internal
DataFrame remove_overlapping_internal(const DataFrame& bedData, const std::string& type);
RcppExport SEXP _rkdMotifs_remove_overlapping_internal(SEXP bedDataSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type bedData(bedDataSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(remove_overlapping_internal(bedData, type));
    return rcpp_result_gen;
END_RCPP
}
// background_internal
List background_internal(const DataFrame& regions, const std::string& regionsType, const DataFrame& excludedRegions, const std::string& excludedRegionsType, int ngcbins, int nrpbins, int nregions, const std::string& referenceFileName);
RcppExport SEXP _rkdMotifs_background_internal(SEXP regionsSEXP, SEXP regionsTypeSEXP, SEXP excludedRegionsSEXP, SEXP excludedRegionsTypeSEXP, SEXP ngcbinsSEXP, SEXP nrpbinsSEXP, SEXP nregionsSEXP, SEXP referenceFileNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type regions(regionsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type regionsType(regionsTypeSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type excludedRegions(excludedRegionsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type excludedRegionsType(excludedRegionsTypeSEXP);
    Rcpp::traits::input_parameter< int >::type ngcbins(ngcbinsSEXP);
    Rcpp::traits::input_parameter< int >::type nrpbins(nrpbinsSEXP);
    Rcpp::traits::input_parameter< int >::type nregions(nregionsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type referenceFileName(referenceFileNameSEXP);
    rcpp_result_gen = Rcpp::wrap(background_internal(regions, regionsType, excludedRegions, excludedRegionsType, ngcbins, nrpbins, nregions, referenceFileName));
    return rcpp_result_gen;
END_RCPP
}
// get_sequences_internal
std::vector<std::string> get_sequences_internal(const DataFrame& bedData, const std::string& type, const std::string fileName);
RcppExport SEXP _rkdMotifs_get_sequences_internal(SEXP bedDataSEXP, SEXP typeSEXP, SEXP fileNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type bedData(bedDataSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type(typeSEXP);
    Rcpp::traits::input_parameter< const std::string >::type fileName(fileNameSEXP);
    rcpp_result_gen = Rcpp::wrap(get_sequences_internal(bedData, type, fileName));
    return rcpp_result_gen;
END_RCPP
}
// kdistr_internal
S4 kdistr_internal(const std::vector<std::string>& sequences, unsigned long kmerlength, unsigned long ngaps, bool doubleStrand, bool estimatekmers, bool strict, bool use_float);
RcppExport SEXP _rkdMotifs_kdistr_internal(SEXP sequencesSEXP, SEXP kmerlengthSEXP, SEXP ngapsSEXP, SEXP doubleStrandSEXP, SEXP estimatekmersSEXP, SEXP strictSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type kmerlength(kmerlengthSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type ngaps(ngapsSEXP);
    Rcpp::traits::input_parameter< bool >::type doubleStrand(doubleStrandSEXP);
    Rcpp::traits::input_parameter< bool >::type estimatekmers(estimatekmersSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdistr_internal(sequences, kmerlength, ngaps, doubleStrand, estimatekmers, strict, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdistrProfile_internal
S4 kdistrProfile_internal(const std::string& sequence, unsigned long win, unsigned long kmerlength, unsigned long ngaps, bool doubleStrand, bool estimatekmers, bool strict, bool use_float);
RcppExport SEXP _rkdMotifs_kdistrProfile_internal(SEXP sequenceSEXP, SEXP winSEXP, SEXP kmerlengthSEXP, SEXP ngapsSEXP, SEXP doubleStrandSEXP, SEXP estimatekmersSEXP, SEXP strictSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type sequence(sequenceSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type win(winSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type kmerlength(kmerlengthSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type ngaps(ngapsSEXP);
    Rcpp::traits::input_parameter< bool >::type doubleStrand(doubleStrandSEXP);
    Rcpp::traits::input_parameter< bool >::type estimatekmers(estimatekmersSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdistrProfile_internal(sequence, win, kmerlength, ngaps, doubleStrand, estimatekmers, strict, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmGkmersString_internal
List kdmGkmersString_internal(unsigned long kmerlength, unsigned long ngaps, bool doubleStrand);
RcppExport SEXP _rkdMotifs_kdmGkmersString_internal(SEXP kmerlengthSEXP, SEXP ngapsSEXP, SEXP doubleStrandSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned long >::type kmerlength(kmerlengthSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type ngaps(ngapsSEXP);
    Rcpp::traits::input_parameter< bool >::type doubleStrand(doubleStrandSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmGkmersString_internal(kmerlength, ngaps, doubleStrand));
    return rcpp_result_gen;
END_RCPP
}
// kdmotifs_internal
S4 kdmotifs_internal(const S4& kdistr, unsigned long rank, unsigned long np, std::string initialization_method, const NumericMatrix& W0, const std::string& clustering_method, bool battacharyya, bool init_only, double tolerance, unsigned long maxIterations, bool use_float);
RcppExport SEXP _rkdMotifs_kdmotifs_internal(SEXP kdistrSEXP, SEXP rankSEXP, SEXP npSEXP, SEXP initialization_methodSEXP, SEXP W0SEXP, SEXP clustering_methodSEXP, SEXP battacharyyaSEXP, SEXP init_onlySEXP, SEXP toleranceSEXP, SEXP maxIterationsSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type kdistr(kdistrSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type rank(rankSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type np(npSEXP);
    Rcpp::traits::input_parameter< std::string >::type initialization_method(initialization_methodSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type W0(W0SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type clustering_method(clustering_methodSEXP);
    Rcpp::traits::input_parameter< bool >::type battacharyya(battacharyyaSEXP);
    Rcpp::traits::input_parameter< bool >::type init_only(init_onlySEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type maxIterations(maxIterationsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmotifs_internal(kdistr, rank, np, initialization_method, W0, clustering_method, battacharyya, init_only, tolerance, maxIterations, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmotifs_from_sequences_internal
S4 kdmotifs_from_sequences_internal(const std::vector<std::string>& sequences, unsigned long kmerlength, unsigned long ngaps, bool double_strand, bool estimate, unsigned long rank, unsigned long np, std::string initialization_method, const NumericMatrix& W0, const std::string& clustering_method, bool battacharyya, bool init_only, double tolerance, unsigned long maxIterations, bool use_float);
RcppExport SEXP _rkdMotifs_kdmotifs_from_sequences_internal(SEXP sequencesSEXP, SEXP kmerlengthSEXP, SEXP ngapsSEXP, SEXP double_strandSEXP, SEXP estimateSEXP, SEXP rankSEXP, SEXP npSEXP, SEXP initialization_methodSEXP, SEXP W0SEXP, SEXP clustering_methodSEXP, SEXP battacharyyaSEXP, SEXP init_onlySEXP, SEXP toleranceSEXP, SEXP maxIterationsSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type kmerlength(kmerlengthSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type ngaps(ngapsSEXP);
    Rcpp::traits::input_parameter< bool >::type double_strand(double_strandSEXP);
    Rcpp::traits::input_parameter< bool >::type estimate(estimateSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type rank(rankSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type np(npSEXP);
    Rcpp::traits::input_parameter< std::string >::type initialization_method(initialization_methodSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type W0(W0SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type clustering_method(clustering_methodSEXP);
    Rcpp::traits::input_parameter< bool >::type battacharyya(battacharyyaSEXP);
    Rcpp::traits::input_parameter< bool >::type init_only(init_onlySEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type maxIterations(maxIterationsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmotifs_from_sequences_internal(sequences, kmerlength, ngaps, double_strand, estimate, rank, np, initialization_method, W0, clustering_method, battacharyya, init_only, tolerance, maxIterations, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmotifs_estimate_internal
S4 kdmotifs_estimate_internal(const S4& motifs, bool use_float);
RcppExport SEXP _rkdMotifs_kdmotifs_estimate_internal(SEXP motifsSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type motifs(motifsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmotifs_estimate_internal(motifs, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmotifs_internal_from_motifs
S4 kdmotifs_internal_from_motifs(const S4& kdmotifs, unsigned long rank, unsigned long np, std::string initialization_method, const NumericMatrix& W0, const std::string& clustering_method, bool battacharyya, bool init_only, double tolerance, unsigned long maxIterations, bool use_float);
RcppExport SEXP _rkdMotifs_kdmotifs_internal_from_motifs(SEXP kdmotifsSEXP, SEXP rankSEXP, SEXP npSEXP, SEXP initialization_methodSEXP, SEXP W0SEXP, SEXP clustering_methodSEXP, SEXP battacharyyaSEXP, SEXP init_onlySEXP, SEXP toleranceSEXP, SEXP maxIterationsSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type kdmotifs(kdmotifsSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type rank(rankSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type np(npSEXP);
    Rcpp::traits::input_parameter< std::string >::type initialization_method(initialization_methodSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type W0(W0SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type clustering_method(clustering_methodSEXP);
    Rcpp::traits::input_parameter< bool >::type battacharyya(battacharyyaSEXP);
    Rcpp::traits::input_parameter< bool >::type init_only(init_onlySEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type maxIterations(maxIterationsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmotifs_internal_from_motifs(kdmotifs, rank, np, initialization_method, W0, clustering_method, battacharyya, init_only, tolerance, maxIterations, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmotifs_merge_internal
S4 kdmotifs_merge_internal(const S4& kdmotifs, const NumericMatrix& labels, unsigned int rank, bool use_float);
RcppExport SEXP _rkdMotifs_kdmotifs_merge_internal(SEXP kdmotifsSEXP, SEXP labelsSEXP, SEXP rankSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type kdmotifs(kdmotifsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type rank(rankSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmotifs_merge_internal(kdmotifs, labels, rank, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmSilhouette_internal
List kdmSilhouette_internal(NumericMatrix& distance, const NumericMatrix& clusterLabels, bool use_float);
RcppExport SEXP _rkdMotifs_kdmSilhouette_internal(SEXP distanceSEXP, SEXP clusterLabelsSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type distance(distanceSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type clusterLabels(clusterLabelsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmSilhouette_internal(distance, clusterLabels, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmGetW0_internal
List kdmGetW0_internal(const S4& counts, const std::string& clustering_method, bool good_clusters, unsigned int minRank, unsigned int maxRank, bool bhattacharyya, bool use_float);
RcppExport SEXP _rkdMotifs_kdmGetW0_internal(SEXP countsSEXP, SEXP clustering_methodSEXP, SEXP good_clustersSEXP, SEXP minRankSEXP, SEXP maxRankSEXP, SEXP bhattacharyyaSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type clustering_method(clustering_methodSEXP);
    Rcpp::traits::input_parameter< bool >::type good_clusters(good_clustersSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type minRank(minRankSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type maxRank(maxRankSEXP);
    Rcpp::traits::input_parameter< bool >::type bhattacharyya(bhattacharyyaSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmGetW0_internal(counts, clustering_method, good_clusters, minRank, maxRank, bhattacharyya, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmRankInfo_internal
List kdmRankInfo_internal(NumericMatrix& distance, const std::string& clustering_method, bool use_float);
RcppExport SEXP _rkdMotifs_kdmRankInfo_internal(SEXP distanceSEXP, SEXP clustering_methodSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type distance(distanceSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type clustering_method(clustering_methodSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmRankInfo_internal(distance, clustering_method, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmotifsfrompwm_internal
S4 kdmotifsfrompwm_internal(const S4& pwmset, unsigned long kmerlength, unsigned long ngaps, bool doubleStrand, unsigned long pad_size, bool use_float);
RcppExport SEXP _rkdMotifs_kdmotifsfrompwm_internal(SEXP pwmsetSEXP, SEXP kmerlengthSEXP, SEXP ngapsSEXP, SEXP doubleStrandSEXP, SEXP pad_sizeSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type pwmset(pwmsetSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type kmerlength(kmerlengthSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type ngaps(ngapsSEXP);
    Rcpp::traits::input_parameter< bool >::type doubleStrand(doubleStrandSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type pad_size(pad_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmotifsfrompwm_internal(pwmset, kmerlength, ngaps, doubleStrand, pad_size, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmotifsfrompwm2_internal
S4 kdmotifsfrompwm2_internal(const S4& pwmset, unsigned long kmerlength, unsigned long ngaps, bool doubleStrand, bool use_float);
RcppExport SEXP _rkdMotifs_kdmotifsfrompwm2_internal(SEXP pwmsetSEXP, SEXP kmerlengthSEXP, SEXP ngapsSEXP, SEXP doubleStrandSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type pwmset(pwmsetSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type kmerlength(kmerlengthSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type ngaps(ngapsSEXP);
    Rcpp::traits::input_parameter< bool >::type doubleStrand(doubleStrandSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmotifsfrompwm2_internal(pwmset, kmerlength, ngaps, doubleStrand, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmGetPWMThresholds_internal
std::vector<double> kdmGetPWMThresholds_internal(const S4& pwmset, double alpha, double initialGranularity, bool forcedGranularity, double maxGranularity);
RcppExport SEXP _rkdMotifs_kdmGetPWMThresholds_internal(SEXP pwmsetSEXP, SEXP alphaSEXP, SEXP initialGranularitySEXP, SEXP forcedGranularitySEXP, SEXP maxGranularitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type pwmset(pwmsetSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type initialGranularity(initialGranularitySEXP);
    Rcpp::traits::input_parameter< bool >::type forcedGranularity(forcedGranularitySEXP);
    Rcpp::traits::input_parameter< double >::type maxGranularity(maxGranularitySEXP);
    rcpp_result_gen = Rcpp::wrap(kdmGetPWMThresholds_internal(pwmset, alpha, initialGranularity, forcedGranularity, maxGranularity));
    return rcpp_result_gen;
END_RCPP
}
// kdmotifsReduce_internal
S4 kdmotifsReduce_internal(const S4& kmotifs, unsigned long rank, double tolerance, unsigned long maxIterations, bool use_float);
RcppExport SEXP _rkdMotifs_kdmotifsReduce_internal(SEXP kmotifsSEXP, SEXP rankSEXP, SEXP toleranceSEXP, SEXP maxIterationsSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type kmotifs(kmotifsSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type rank(rankSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type maxIterations(maxIterationsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmotifsReduce_internal(kmotifs, rank, tolerance, maxIterations, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdfeatures_internal_from_kdistr
S4 kdfeatures_internal_from_kdistr(const S4& motifs, const S4& kdistr, bool use_float);
RcppExport SEXP _rkdMotifs_kdfeatures_internal_from_kdistr(SEXP motifsSEXP, SEXP kdistrSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type motifs(motifsSEXP);
    Rcpp::traits::input_parameter< const S4& >::type kdistr(kdistrSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdfeatures_internal_from_kdistr(motifs, kdistr, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdfeatures_internal_from_seqs
S4 kdfeatures_internal_from_seqs(const S4& motifs, const std::vector<std::string>& sequences, bool strict, bool use_float);
RcppExport SEXP _rkdMotifs_kdfeatures_internal_from_seqs(SEXP motifsSEXP, SEXP sequencesSEXP, SEXP strictSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type motifs(motifsSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdfeatures_internal_from_seqs(motifs, sequences, strict, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdfeatures_profile_internal
S4 kdfeatures_profile_internal(const S4& motifs, const std::string& sequence, unsigned long win, bool strict, bool use_float);
RcppExport SEXP _rkdMotifs_kdfeatures_profile_internal(SEXP motifsSEXP, SEXP sequenceSEXP, SEXP winSEXP, SEXP strictSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type motifs(motifsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type sequence(sequenceSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type win(winSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdfeatures_profile_internal(motifs, sequence, win, strict, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmToKdistr_internal
S4 kdmToKdistr_internal(const S4& m, bool use_float);
RcppExport SEXP _rkdMotifs_kdmToKdistr_internal(SEXP mSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type m(mSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmToKdistr_internal(m, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmToKDMotifs_internal
S4 kdmToKDMotifs_internal(const S4& d, bool use_float);
RcppExport SEXP _rkdMotifs_kdmToKDMotifs_internal(SEXP dSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type d(dSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmToKDMotifs_internal(d, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmSimilarity_kdistr_internal
NumericMatrix kdmSimilarity_kdistr_internal(const S4& d1, const S4& d2, bool use_float);
RcppExport SEXP _rkdMotifs_kdmSimilarity_kdistr_internal(SEXP d1SEXP, SEXP d2SEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< const S4& >::type d2(d2SEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmSimilarity_kdistr_internal(d1, d2, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmSimilarity_kdmotifs_internal
NumericMatrix kdmSimilarity_kdmotifs_internal(const S4& d1, const S4& d2, bool use_float);
RcppExport SEXP _rkdMotifs_kdmSimilarity_kdmotifs_internal(SEXP d1SEXP, SEXP d2SEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< const S4& >::type d2(d2SEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmSimilarity_kdmotifs_internal(d1, d2, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmDistance_kdistr_internal
NumericMatrix kdmDistance_kdistr_internal(const S4& d1, const S4& d2, bool bhattacharyya, bool use_float);
RcppExport SEXP _rkdMotifs_kdmDistance_kdistr_internal(SEXP d1SEXP, SEXP d2SEXP, SEXP bhattacharyyaSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< const S4& >::type d2(d2SEXP);
    Rcpp::traits::input_parameter< bool >::type bhattacharyya(bhattacharyyaSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmDistance_kdistr_internal(d1, d2, bhattacharyya, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmDistance_kdmotifs_internal
NumericMatrix kdmDistance_kdmotifs_internal(const S4& d1, const S4& d2, bool bhattacharyya, bool use_float);
RcppExport SEXP _rkdMotifs_kdmDistance_kdmotifs_internal(SEXP d1SEXP, SEXP d2SEXP, SEXP bhattacharyyaSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< const S4& >::type d2(d2SEXP);
    Rcpp::traits::input_parameter< bool >::type bhattacharyya(bhattacharyyaSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmDistance_kdmotifs_internal(d1, d2, bhattacharyya, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmSimilarity_kdistr_self_internal
NumericMatrix kdmSimilarity_kdistr_self_internal(const S4& d1, bool use_float);
RcppExport SEXP _rkdMotifs_kdmSimilarity_kdistr_self_internal(SEXP d1SEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmSimilarity_kdistr_self_internal(d1, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmSimilarity_kdmotifs_self_internal
NumericMatrix kdmSimilarity_kdmotifs_self_internal(const S4& d1, bool use_float);
RcppExport SEXP _rkdMotifs_kdmSimilarity_kdmotifs_self_internal(SEXP d1SEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmSimilarity_kdmotifs_self_internal(d1, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmDistance_kdistr_self_internal
NumericMatrix kdmDistance_kdistr_self_internal(const S4& d1, bool bhattacharyya, bool use_float);
RcppExport SEXP _rkdMotifs_kdmDistance_kdistr_self_internal(SEXP d1SEXP, SEXP bhattacharyyaSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< bool >::type bhattacharyya(bhattacharyyaSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmDistance_kdistr_self_internal(d1, bhattacharyya, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmDistance_kdmotifs_self_internal
NumericMatrix kdmDistance_kdmotifs_self_internal(const S4& d1, bool bhattacharyya, bool use_float);
RcppExport SEXP _rkdMotifs_kdmDistance_kdmotifs_self_internal(SEXP d1SEXP, SEXP bhattacharyyaSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< bool >::type bhattacharyya(bhattacharyyaSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmDistance_kdmotifs_self_internal(d1, bhattacharyya, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmModelCorrelation_internal
List kdmModelCorrelation_internal(const S4& a, const S4& b, unsigned long niter, bool use_float);
RcppExport SEXP _rkdMotifs_kdmModelCorrelation_internal(SEXP aSEXP, SEXP bSEXP, SEXP niterSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const S4& >::type b(bSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmModelCorrelation_internal(a, b, niter, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmModelCorrelation2_internal
List kdmModelCorrelation2_internal(const S4& a, const S4& b, unsigned long niter, bool use_float);
RcppExport SEXP _rkdMotifs_kdmModelCorrelation2_internal(SEXP aSEXP, SEXP bSEXP, SEXP niterSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const S4& >::type b(bSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmModelCorrelation2_internal(a, b, niter, use_float));
    return rcpp_result_gen;
END_RCPP
}
// predict_internal_from_features
NumericMatrix predict_internal_from_features(const S4 model, const S4 features, bool use_float);
RcppExport SEXP _rkdMotifs_predict_internal_from_features(SEXP modelSEXP, SEXP featuresSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4 >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const S4 >::type features(featuresSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_internal_from_features(model, features, use_float));
    return rcpp_result_gen;
END_RCPP
}
// predict_internal_from_kdistr
NumericMatrix predict_internal_from_kdistr(const S4 model, const S4 kdistr, bool use_float);
RcppExport SEXP _rkdMotifs_predict_internal_from_kdistr(SEXP modelSEXP, SEXP kdistrSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4 >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const S4 >::type kdistr(kdistrSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_internal_from_kdistr(model, kdistr, use_float));
    return rcpp_result_gen;
END_RCPP
}
// predict_internal_from_sequences
NumericMatrix predict_internal_from_sequences(const S4 model, const std::vector<std::string>& sequences, bool strict, bool use_float);
RcppExport SEXP _rkdMotifs_predict_internal_from_sequences(SEXP modelSEXP, SEXP sequencesSEXP, SEXP strictSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4 >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_internal_from_sequences(model, sequences, strict, use_float));
    return rcpp_result_gen;
END_RCPP
}
// predict_internal_from_bed
NumericMatrix predict_internal_from_bed(const S4 model, const DataFrame& bedData, const std::string& bedType, const std::string& filename, bool strict, bool use_float);
RcppExport SEXP _rkdMotifs_predict_internal_from_bed(SEXP modelSEXP, SEXP bedDataSEXP, SEXP bedTypeSEXP, SEXP filenameSEXP, SEXP strictSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4 >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type bedData(bedDataSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type bedType(bedTypeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_internal_from_bed(model, bedData, bedType, filename, strict, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmLoadPWMSet
S4 kdmLoadPWMSet(const std::string filename);
RcppExport SEXP _rkdMotifs_kdmLoadPWMSet(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmLoadPWMSet(filename));
    return rcpp_result_gen;
END_RCPP
}
// kdmFeaturesFromPWMSet_internal
NumericMatrix kdmFeaturesFromPWMSet_internal(const std::vector<std::string>& sequences, const S4& pwmset, bool double_strand, const std::string& mode);
RcppExport SEXP _rkdMotifs_kdmFeaturesFromPWMSet_internal(SEXP sequencesSEXP, SEXP pwmsetSEXP, SEXP double_strandSEXP, SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< const S4& >::type pwmset(pwmsetSEXP);
    Rcpp::traits::input_parameter< bool >::type double_strand(double_strandSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type mode(modeSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmFeaturesFromPWMSet_internal(sequences, pwmset, double_strand, mode));
    return rcpp_result_gen;
END_RCPP
}
// kdmFeaturesProfileFromPWMSet_internal
NumericMatrix kdmFeaturesProfileFromPWMSet_internal(const std::string& sequence, const S4& pwmset);
RcppExport SEXP _rkdMotifs_kdmFeaturesProfileFromPWMSet_internal(SEXP sequenceSEXP, SEXP pwmsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type sequence(sequenceSEXP);
    Rcpp::traits::input_parameter< const S4& >::type pwmset(pwmsetSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmFeaturesProfileFromPWMSet_internal(sequence, pwmset));
    return rcpp_result_gen;
END_RCPP
}
// kdmMotifProfiles2_internal
List kdmMotifProfiles2_internal(const DataFrame& bedData, const std::vector<unsigned int>& centers, const std::vector<unsigned int>& labels, const S4& motifs, unsigned int halfInterval, unsigned int halfWin, std::string genomeFile, bool strict, bool use_float);
RcppExport SEXP _rkdMotifs_kdmMotifProfiles2_internal(SEXP bedDataSEXP, SEXP centersSEXP, SEXP labelsSEXP, SEXP motifsSEXP, SEXP halfIntervalSEXP, SEXP halfWinSEXP, SEXP genomeFileSEXP, SEXP strictSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type bedData(bedDataSEXP);
    Rcpp::traits::input_parameter< const std::vector<unsigned int>& >::type centers(centersSEXP);
    Rcpp::traits::input_parameter< const std::vector<unsigned int>& >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< const S4& >::type motifs(motifsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type halfInterval(halfIntervalSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type halfWin(halfWinSEXP);
    Rcpp::traits::input_parameter< std::string >::type genomeFile(genomeFileSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmMotifProfiles2_internal(bedData, centers, labels, motifs, halfInterval, halfWin, genomeFile, strict, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmMotifProfiles3_internal
List kdmMotifProfiles3_internal(const DataFrame& bedData, const std::vector<unsigned int>& centers, const std::vector<unsigned int>& labels, const S4& motifs, unsigned int halfInterval, unsigned int halfWin, std::string genomeFile, bool strict, bool use_float);
RcppExport SEXP _rkdMotifs_kdmMotifProfiles3_internal(SEXP bedDataSEXP, SEXP centersSEXP, SEXP labelsSEXP, SEXP motifsSEXP, SEXP halfIntervalSEXP, SEXP halfWinSEXP, SEXP genomeFileSEXP, SEXP strictSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type bedData(bedDataSEXP);
    Rcpp::traits::input_parameter< const std::vector<unsigned int>& >::type centers(centersSEXP);
    Rcpp::traits::input_parameter< const std::vector<unsigned int>& >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< const S4& >::type motifs(motifsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type halfInterval(halfIntervalSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type halfWin(halfWinSEXP);
    Rcpp::traits::input_parameter< std::string >::type genomeFile(genomeFileSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmMotifProfiles3_internal(bedData, centers, labels, motifs, halfInterval, halfWin, genomeFile, strict, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmMotifProfiles3_seq_internal
List kdmMotifProfiles3_seq_internal(const std::vector<std::string>& pseq, const std::vector<std::string>& nseq, const S4& motifs, unsigned int halfInterval, unsigned int halfWin, bool strict, bool use_float);
RcppExport SEXP _rkdMotifs_kdmMotifProfiles3_seq_internal(SEXP pseqSEXP, SEXP nseqSEXP, SEXP motifsSEXP, SEXP halfIntervalSEXP, SEXP halfWinSEXP, SEXP strictSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type pseq(pseqSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type nseq(nseqSEXP);
    Rcpp::traits::input_parameter< const S4& >::type motifs(motifsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type halfInterval(halfIntervalSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type halfWin(halfWinSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmMotifProfiles3_seq_internal(pseq, nseq, motifs, halfInterval, halfWin, strict, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmGetProfilesParameters_internal
NumericMatrix kdmGetProfilesParameters_internal(const List& profile, unsigned int halfInterval, unsigned int halfWin, unsigned int nrep, unsigned int maxSelectedPeak, unsigned int half90Interval, bool use_float);
RcppExport SEXP _rkdMotifs_kdmGetProfilesParameters_internal(SEXP profileSEXP, SEXP halfIntervalSEXP, SEXP halfWinSEXP, SEXP nrepSEXP, SEXP maxSelectedPeakSEXP, SEXP half90IntervalSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type profile(profileSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type halfInterval(halfIntervalSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type halfWin(halfWinSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nrep(nrepSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type maxSelectedPeak(maxSelectedPeakSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type half90Interval(half90IntervalSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmGetProfilesParameters_internal(profile, halfInterval, halfWin, nrep, maxSelectedPeak, half90Interval, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmMotifProfiles_internal
List kdmMotifProfiles_internal(const DataFrame& bedData, const std::vector<unsigned int>& centers, const std::vector<unsigned int>& labels, const S4& motifs, unsigned int interval, unsigned int win, unsigned int nrep, unsigned int maxSelectedPeak, unsigned int half90interval, std::string genomeFile, bool use_float);
RcppExport SEXP _rkdMotifs_kdmMotifProfiles_internal(SEXP bedDataSEXP, SEXP centersSEXP, SEXP labelsSEXP, SEXP motifsSEXP, SEXP intervalSEXP, SEXP winSEXP, SEXP nrepSEXP, SEXP maxSelectedPeakSEXP, SEXP half90intervalSEXP, SEXP genomeFileSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type bedData(bedDataSEXP);
    Rcpp::traits::input_parameter< const std::vector<unsigned int>& >::type centers(centersSEXP);
    Rcpp::traits::input_parameter< const std::vector<unsigned int>& >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< const S4& >::type motifs(motifsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type interval(intervalSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type win(winSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nrep(nrepSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type maxSelectedPeak(maxSelectedPeakSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type half90interval(half90intervalSEXP);
    Rcpp::traits::input_parameter< std::string >::type genomeFile(genomeFileSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmMotifProfiles_internal(bedData, centers, labels, motifs, interval, win, nrep, maxSelectedPeak, half90interval, genomeFile, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmGetPWM_internal
NumericMatrix kdmGetPWM_internal(const S4& W, unsigned len, const std::vector<double>& pwm0, double tol, unsigned maxIter, bool use_float);
RcppExport SEXP _rkdMotifs_kdmGetPWM_internal(SEXP WSEXP, SEXP lenSEXP, SEXP pwm0SEXP, SEXP tolSEXP, SEXP maxIterSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type W(WSEXP);
    Rcpp::traits::input_parameter< unsigned >::type len(lenSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type pwm0(pwm0SEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< unsigned >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmGetPWM_internal(W, len, pwm0, tol, maxIter, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmProfileInfo_internal
List kdmProfileInfo_internal(const S4& motifs, const DataFrame& regions, const std::vector<unsigned int>& centers, const std::vector<unsigned int>& labels, const std::string& genomeFile, unsigned int halfInterval, unsigned int halfWin, double tolerance, bool strict, bool use_float);
RcppExport SEXP _rkdMotifs_kdmProfileInfo_internal(SEXP motifsSEXP, SEXP regionsSEXP, SEXP centersSEXP, SEXP labelsSEXP, SEXP genomeFileSEXP, SEXP halfIntervalSEXP, SEXP halfWinSEXP, SEXP toleranceSEXP, SEXP strictSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type motifs(motifsSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type regions(regionsSEXP);
    Rcpp::traits::input_parameter< const std::vector<unsigned int>& >::type centers(centersSEXP);
    Rcpp::traits::input_parameter< const std::vector<unsigned int>& >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type genomeFile(genomeFileSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type halfInterval(halfIntervalSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type halfWin(halfWinSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmProfileInfo_internal(motifs, regions, centers, labels, genomeFile, halfInterval, halfWin, tolerance, strict, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmProfileInfoSeq_internal
List kdmProfileInfoSeq_internal(const S4& motifs, const std::vector<std::string>& pseq, const std::vector<std::string>& nseq, unsigned int halfInterval, unsigned int halfWin, double tolerance, bool strict, bool use_float);
RcppExport SEXP _rkdMotifs_kdmProfileInfoSeq_internal(SEXP motifsSEXP, SEXP pseqSEXP, SEXP nseqSEXP, SEXP halfIntervalSEXP, SEXP halfWinSEXP, SEXP toleranceSEXP, SEXP strictSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type motifs(motifsSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type pseq(pseqSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type nseq(nseqSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type halfInterval(halfIntervalSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type halfWin(halfWinSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmProfileInfoSeq_internal(motifs, pseq, nseq, halfInterval, halfWin, tolerance, strict, use_float));
    return rcpp_result_gen;
END_RCPP
}
// kdmCentrimo_internal
List kdmCentrimo_internal(const IntegerMatrix& pcounts, const IntegerMatrix& ncounts, unsigned int npseqs, unsigned int nnseqs, std::string tail, bool symmetric, bool use_float);
RcppExport SEXP _rkdMotifs_kdmCentrimo_internal(SEXP pcountsSEXP, SEXP ncountsSEXP, SEXP npseqsSEXP, SEXP nnseqsSEXP, SEXP tailSEXP, SEXP symmetricSEXP, SEXP use_floatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type pcounts(pcountsSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type ncounts(ncountsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type npseqs(npseqsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nnseqs(nnseqsSEXP);
    Rcpp::traits::input_parameter< std::string >::type tail(tailSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< bool >::type use_float(use_floatSEXP);
    rcpp_result_gen = Rcpp::wrap(kdmCentrimo_internal(pcounts, ncounts, npseqs, nnseqs, tail, symmetric, use_float));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rkdMotifs_setCudaUsage", (DL_FUNC) &_rkdMotifs_setCudaUsage, 1},
    {"_rkdMotifs_setNCores", (DL_FUNC) &_rkdMotifs_setNCores, 1},
    {"_rkdMotifs_setVerbosity", (DL_FUNC) &_rkdMotifs_setVerbosity, 1},
    {"_rkdMotifs_setgMethodsSeed", (DL_FUNC) &_rkdMotifs_setgMethodsSeed, 1},
    {"_rkdMotifs_test_convert_internal", (DL_FUNC) &_rkdMotifs_test_convert_internal, 1},
    {"_rkdMotifs_readBedFile_internal", (DL_FUNC) &_rkdMotifs_readBedFile_internal, 2},
    {"_rkdMotifs_remove_overlapping_internal", (DL_FUNC) &_rkdMotifs_remove_overlapping_internal, 2},
    {"_rkdMotifs_background_internal", (DL_FUNC) &_rkdMotifs_background_internal, 8},
    {"_rkdMotifs_get_sequences_internal", (DL_FUNC) &_rkdMotifs_get_sequences_internal, 3},
    {"_rkdMotifs_kdistr_internal", (DL_FUNC) &_rkdMotifs_kdistr_internal, 7},
    {"_rkdMotifs_kdistrProfile_internal", (DL_FUNC) &_rkdMotifs_kdistrProfile_internal, 8},
    {"_rkdMotifs_kdmGkmersString_internal", (DL_FUNC) &_rkdMotifs_kdmGkmersString_internal, 3},
    {"_rkdMotifs_kdmotifs_internal", (DL_FUNC) &_rkdMotifs_kdmotifs_internal, 11},
    {"_rkdMotifs_kdmotifs_from_sequences_internal", (DL_FUNC) &_rkdMotifs_kdmotifs_from_sequences_internal, 15},
    {"_rkdMotifs_kdmotifs_estimate_internal", (DL_FUNC) &_rkdMotifs_kdmotifs_estimate_internal, 2},
    {"_rkdMotifs_kdmotifs_internal_from_motifs", (DL_FUNC) &_rkdMotifs_kdmotifs_internal_from_motifs, 11},
    {"_rkdMotifs_kdmotifs_merge_internal", (DL_FUNC) &_rkdMotifs_kdmotifs_merge_internal, 4},
    {"_rkdMotifs_kdmSilhouette_internal", (DL_FUNC) &_rkdMotifs_kdmSilhouette_internal, 3},
    {"_rkdMotifs_kdmGetW0_internal", (DL_FUNC) &_rkdMotifs_kdmGetW0_internal, 7},
    {"_rkdMotifs_kdmRankInfo_internal", (DL_FUNC) &_rkdMotifs_kdmRankInfo_internal, 3},
    {"_rkdMotifs_kdmotifsfrompwm_internal", (DL_FUNC) &_rkdMotifs_kdmotifsfrompwm_internal, 6},
    {"_rkdMotifs_kdmotifsfrompwm2_internal", (DL_FUNC) &_rkdMotifs_kdmotifsfrompwm2_internal, 5},
    {"_rkdMotifs_kdmGetPWMThresholds_internal", (DL_FUNC) &_rkdMotifs_kdmGetPWMThresholds_internal, 5},
    {"_rkdMotifs_kdmotifsReduce_internal", (DL_FUNC) &_rkdMotifs_kdmotifsReduce_internal, 5},
    {"_rkdMotifs_kdfeatures_internal_from_kdistr", (DL_FUNC) &_rkdMotifs_kdfeatures_internal_from_kdistr, 3},
    {"_rkdMotifs_kdfeatures_internal_from_seqs", (DL_FUNC) &_rkdMotifs_kdfeatures_internal_from_seqs, 4},
    {"_rkdMotifs_kdfeatures_profile_internal", (DL_FUNC) &_rkdMotifs_kdfeatures_profile_internal, 5},
    {"_rkdMotifs_kdmToKdistr_internal", (DL_FUNC) &_rkdMotifs_kdmToKdistr_internal, 2},
    {"_rkdMotifs_kdmToKDMotifs_internal", (DL_FUNC) &_rkdMotifs_kdmToKDMotifs_internal, 2},
    {"_rkdMotifs_kdmSimilarity_kdistr_internal", (DL_FUNC) &_rkdMotifs_kdmSimilarity_kdistr_internal, 3},
    {"_rkdMotifs_kdmSimilarity_kdmotifs_internal", (DL_FUNC) &_rkdMotifs_kdmSimilarity_kdmotifs_internal, 3},
    {"_rkdMotifs_kdmDistance_kdistr_internal", (DL_FUNC) &_rkdMotifs_kdmDistance_kdistr_internal, 4},
    {"_rkdMotifs_kdmDistance_kdmotifs_internal", (DL_FUNC) &_rkdMotifs_kdmDistance_kdmotifs_internal, 4},
    {"_rkdMotifs_kdmSimilarity_kdistr_self_internal", (DL_FUNC) &_rkdMotifs_kdmSimilarity_kdistr_self_internal, 2},
    {"_rkdMotifs_kdmSimilarity_kdmotifs_self_internal", (DL_FUNC) &_rkdMotifs_kdmSimilarity_kdmotifs_self_internal, 2},
    {"_rkdMotifs_kdmDistance_kdistr_self_internal", (DL_FUNC) &_rkdMotifs_kdmDistance_kdistr_self_internal, 3},
    {"_rkdMotifs_kdmDistance_kdmotifs_self_internal", (DL_FUNC) &_rkdMotifs_kdmDistance_kdmotifs_self_internal, 3},
    {"_rkdMotifs_kdmModelCorrelation_internal", (DL_FUNC) &_rkdMotifs_kdmModelCorrelation_internal, 4},
    {"_rkdMotifs_kdmModelCorrelation2_internal", (DL_FUNC) &_rkdMotifs_kdmModelCorrelation2_internal, 4},
    {"_rkdMotifs_predict_internal_from_features", (DL_FUNC) &_rkdMotifs_predict_internal_from_features, 3},
    {"_rkdMotifs_predict_internal_from_kdistr", (DL_FUNC) &_rkdMotifs_predict_internal_from_kdistr, 3},
    {"_rkdMotifs_predict_internal_from_sequences", (DL_FUNC) &_rkdMotifs_predict_internal_from_sequences, 4},
    {"_rkdMotifs_predict_internal_from_bed", (DL_FUNC) &_rkdMotifs_predict_internal_from_bed, 6},
    {"_rkdMotifs_kdmLoadPWMSet", (DL_FUNC) &_rkdMotifs_kdmLoadPWMSet, 1},
    {"_rkdMotifs_kdmFeaturesFromPWMSet_internal", (DL_FUNC) &_rkdMotifs_kdmFeaturesFromPWMSet_internal, 4},
    {"_rkdMotifs_kdmFeaturesProfileFromPWMSet_internal", (DL_FUNC) &_rkdMotifs_kdmFeaturesProfileFromPWMSet_internal, 2},
    {"_rkdMotifs_kdmMotifProfiles2_internal", (DL_FUNC) &_rkdMotifs_kdmMotifProfiles2_internal, 9},
    {"_rkdMotifs_kdmMotifProfiles3_internal", (DL_FUNC) &_rkdMotifs_kdmMotifProfiles3_internal, 9},
    {"_rkdMotifs_kdmMotifProfiles3_seq_internal", (DL_FUNC) &_rkdMotifs_kdmMotifProfiles3_seq_internal, 7},
    {"_rkdMotifs_kdmGetProfilesParameters_internal", (DL_FUNC) &_rkdMotifs_kdmGetProfilesParameters_internal, 7},
    {"_rkdMotifs_kdmMotifProfiles_internal", (DL_FUNC) &_rkdMotifs_kdmMotifProfiles_internal, 11},
    {"_rkdMotifs_kdmGetPWM_internal", (DL_FUNC) &_rkdMotifs_kdmGetPWM_internal, 6},
    {"_rkdMotifs_kdmProfileInfo_internal", (DL_FUNC) &_rkdMotifs_kdmProfileInfo_internal, 10},
    {"_rkdMotifs_kdmProfileInfoSeq_internal", (DL_FUNC) &_rkdMotifs_kdmProfileInfoSeq_internal, 8},
    {"_rkdMotifs_kdmCentrimo_internal", (DL_FUNC) &_rkdMotifs_kdmCentrimo_internal, 7},
    {NULL, NULL, 0}
};

void initPackage(DllInfo* dll);
RcppExport void R_init_rkdMotifs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    initPackage(dll);
}
